### ISSUE TITLE
Upper snake case with number not recognized as common case

### ISSUE THREAD

**Issue by teopiaz** [jasujm/enhanced-enum#4]
If the enumeration value in upper snake case contains a number like:
THIS_IS_A_TEST_123
THIS_123_IS_123_A_123_TEST
The NameFormatter is throwing an exception
```
>>> from enumecg.utils import NameFormatter
>>> form =NameFormatter("THIS_WORKS123", "THIS_BREAK_123")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/enhanced-enum/python/enumecg/utils.py", line 113, in __init__
    raise exceptions.Error(f"Could not find common case for {names!r}")
enumecg.exceptions.Error: Could not find common case for ('THIS_WORKS123', 'THIS_BREAK_123')
```

**Comment by jasujm** [comment]
Hi @teopiaz,

Thanks for reporting this :). Indeed, there should be support for snake-cased identifiers with numeric parts. I fixed it and published a new version of `EnumECG`.
